### ISSUE TITLE
Visualize gateway instances

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/gravitee-management-webui#133]
Gateway instances must be accessible from a new menu item "gateways / instances".
Admin must be able to:
* See running instances
* See unknown-state instances
* Instances informations : IP / host / ...
* Show system properties for a given instance

**Comment by aelamrani** [comment]
Closed by https://github.com/gravitee-io/gravitee-management-webui/commit/e6ab12c4fbde704e89e57e2181623bb6c8b33371
