### ISSUE TITLE
Specialize some CORS directives

### ISSUE THREAD

**Issue by bcollard** [gravitee-io/gravitee-management-webui#136]
Please, can you improve the UI in the CORS policy to help administrators with these features:
- accessControlAllowOrigin
  - when a client send "withCredentials:true" in the preflight request, you *may* return the same value of HTTP request "Origin" in the HTTP response "Access-Control-Allow-Origin". 
  - when a client does not send "withCredentials:true", then you *can* return "*" in the HTTP response "Access-Control-Allow-origin".

- accessControlAllowMethods
  - provide an easy way to enable / disable HTTP verbs. Can be similar to the methods allowed at the policy level.

**Comment by brasseld** [comment]
This issue was moved to gravitee-io/gravitee-policy-cors#1
