### ISSUE TITLE
Login function is not defined

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/gravitee-management-webui#164]
![no-api-login](https://cloud.githubusercontent.com/assets/1927438/15800679/54abb2e2-2a80-11e6-8283-71d6cc3efb6e.png)

If the Gravitee.io Portal has no API and we want to log in, we get the following error :

_angular.js:12783 TypeError: _that.showLoginModal is not a function
    at sidenav.directive.js:67_

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-management-webui/pull/165/commits
