### ISSUE TITLE
"API out of sync" message when loading admin page of an API

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/gravitee-management-webui#56]
This occurs only during page loading, event if there is no need to redeploy the API.
<img width="1440" alt="capture d ecran 2016-01-12 a 17 23 34" src="https://cloud.githubusercontent.com/assets/133094/12269398/7a0ce448-b951-11e5-9866-579ee55e4907.png">

**Comment by tcompiegne** [comment]
@brasseld The issue is still reproducible ?

**Comment by brasseld** [comment]
@tcompiegne : yes if the server takes a long time to respond.
I think it's because the banner is based on ng-hide instead of ng-show...

**Comment by brasseld** [comment]
@tcompiegne : It seems that this issue can not be reproduce with 0.7.0 nightly build

**Comment by brasseld** [comment]
Not reproductible with latest build.
Closing it.
