### ISSUE TITLE
Too much clic to create yout first api

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/gravitee-management-webui#64]
the "Create your first API" button on the welcome page, redirect to the "apis/thumb" page when you need to clic a second time on the buton

**Comment by brasseld** [comment]
This is because you have no API. 
The "create your first API" is only available in that case.

**Comment by NicolasGeraud** [comment]
Yes, but the button on the welcome page must redirect to the dialog box, not the thumb page.
