### ISSUE TITLE
No validation messages in API Form

### ISSUE THREAD

**Issue by M3lkior** [gravitee-io/gravitee-management-webui#85]
I can not create a new api but i don't know why ...
It will be more confortable to have description messages when fields are on error : 

![pasted image at 2016_02_08 01_53 pm](https://cloud.githubusercontent.com/assets/5501911/12886229/1c5f9d10-ce6c-11e5-8ebc-fd57aee0ef55.png)

**Comment by brasseld** [comment]
This issue was moved to gravitee-io/ichiou#20
