### ISSUE TITLE
RAML Doc parsing issue

### ISSUE THREAD

**Issue by M3lkior** [gravitee-io/gravitee-management-webui#86]
I try to add a RAML Doc based on this : http://raml.org/developers/raml-200-tutorial#base-raml-file

The web-ui show an ERROR WHILE PARSING error

![raml](https://cloud.githubusercontent.com/assets/5501911/12915391/1a9b22a0-cf2b-11e5-891e-4ba99f41cfec.png)

**Comment by brasseld** [comment]
Your RAML is not valid because it does not contain RAML header.

**Comment by M3lkior** [comment]
Trying to import this file from raml-org also throw a parsing error ...

https://github.com/raml-org/raml-tutorial-200/blob/master/jukebox-api.raml

**Comment by brasseld** [comment]
And it's due to the includes which are not resolved.
